[package]
name = "homelumen-app"
description = "HomeLumen desktop interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "homelumen"
path = "src/main.rs"

[dependencies]
homelumen-core.workspace = true
homelumen-engine.workspace = true

iced = { version = "0.14", features = ["advanced", "canvas", "tokio"] }
sys-locale = "0.3.2"

[build-dependencies]
winresource = "0.1.31"

[package.metadata.packager]
product-name = "Home Lumen"
identifier = "io.github.victor-root.homelumen"
publisher = "The HomeLumen contributors"
homepage = "https://github.com/Victor-root/HomeLumen"
before-packaging-command = "cargo build --release"
formats = ["nsis"]
resources = ["../../LICENSE"]

[package.metadata.packager.nsis]
installer-icon = "../../assets/icon/icon.ico"
installer-mode = "perMachine"
languages = ["English", "French"]
